version: '3'
services:
  mysql:
    image: mysql:5.7
    hostname: go_mysql
    container_name: go_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: imdeo
      MYSQL_DATABASE: imdeo
